//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWpfClient.EmployeeServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.DTO")]
    [System.SerializableAttribute()]
    public partial class DepartmentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.DTO")]
    [System.SerializableAttribute()]
    public partial class EmployeeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeWpfClient.EmployeeServiceRef.DepartmentDto DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeWpfClient.EmployeeServiceRef.ProjectDto[] ProjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeWpfClient.EmployeeServiceRef.DepartmentDto Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeWpfClient.EmployeeServiceRef.ProjectDto[] Projects {
            get {
                return this.ProjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectsField, value) != true)) {
                    this.ProjectsField = value;
                    this.RaisePropertyChanged("Projects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDetailDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.DTO")]
    [System.SerializableAttribute()]
    public partial class EmployeeDetailDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeDetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeDetailId {
            get {
                return this.EmployeeDetailIdField;
            }
            set {
                if ((this.EmployeeDetailIdField.Equals(value) != true)) {
                    this.EmployeeDetailIdField = value;
                    this.RaisePropertyChanged("EmployeeDetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDto", Namespace="http://schemas.datacontract.org/2004/07/Learn.DTO")]
    [System.SerializableAttribute()]
    public partial class ProjectDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceRef.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllDepartments", ReplyAction="http://tempuri.org/IEmployeeService/GetAllDepartmentsResponse")]
        EmployeeWpfClient.EmployeeServiceRef.DepartmentDto[] GetAllDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllDepartments", ReplyAction="http://tempuri.org/IEmployeeService/GetAllDepartmentsResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto[]> GetAllDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetDepartmentById", ReplyAction="http://tempuri.org/IEmployeeService/GetDepartmentByIdResponse")]
        EmployeeWpfClient.EmployeeServiceRef.DepartmentDto GetDepartmentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetDepartmentById", ReplyAction="http://tempuri.org/IEmployeeService/GetDepartmentByIdResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> GetDepartmentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateDepartment", ReplyAction="http://tempuri.org/IEmployeeService/CreateDepartmentResponse")]
        EmployeeWpfClient.EmployeeServiceRef.DepartmentDto CreateDepartment(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateDepartment", ReplyAction="http://tempuri.org/IEmployeeService/CreateDepartmentResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> CreateDepartmentAsync(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateDepartment", ReplyAction="http://tempuri.org/IEmployeeService/UpdateDepartmentResponse")]
        EmployeeWpfClient.EmployeeServiceRef.DepartmentDto UpdateDepartment(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateDepartment", ReplyAction="http://tempuri.org/IEmployeeService/UpdateDepartmentResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> UpdateDepartmentAsync(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteDepartment", ReplyAction="http://tempuri.org/IEmployeeService/DeleteDepartmentResponse")]
        bool DeleteDepartment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteDepartment", ReplyAction="http://tempuri.org/IEmployeeService/DeleteDepartmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteDepartmentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetAllEmployeesResponse")]
        EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[]> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeesByDepartmentId", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeesByDepartmentIdResponse")]
        EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] GetEmployeesByDepartmentId(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeesByDepartmentId", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeesByDepartmentIdResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[]> GetEmployeesByDepartmentIdAsync(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIdResponse")]
        EmployeeWpfClient.EmployeeServiceRef.EmployeeDto GetEmployeeById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIdResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto> GetEmployeeByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/CreateEmployeeResponse")]
        EmployeeWpfClient.EmployeeServiceRef.EmployeeDto CreateEmployee(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto> CreateEmployeeAsync(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/UpdateEmployeeResponse")]
        EmployeeWpfClient.EmployeeServiceRef.EmployeeDto UpdateEmployee(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto> UpdateEmployeeAsync(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeService/DeleteEmployeeResponse")]
        bool DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeDetail", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeDetailResponse")]
        EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto GetEmployeeDetail(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeDetail", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeDetailResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto> GetEmployeeDetailAsync(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateOrUpdateEmployeeDetail", ReplyAction="http://tempuri.org/IEmployeeService/CreateOrUpdateEmployeeDetailResponse")]
        EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto CreateOrUpdateEmployeeDetail(EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateOrUpdateEmployeeDetail", ReplyAction="http://tempuri.org/IEmployeeService/CreateOrUpdateEmployeeDetailResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto> CreateOrUpdateEmployeeDetailAsync(EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllProjects", ReplyAction="http://tempuri.org/IEmployeeService/GetAllProjectsResponse")]
        EmployeeWpfClient.EmployeeServiceRef.ProjectDto[] GetAllProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllProjects", ReplyAction="http://tempuri.org/IEmployeeService/GetAllProjectsResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto[]> GetAllProjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetProjectById", ReplyAction="http://tempuri.org/IEmployeeService/GetProjectByIdResponse")]
        EmployeeWpfClient.EmployeeServiceRef.ProjectDto GetProjectById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetProjectById", ReplyAction="http://tempuri.org/IEmployeeService/GetProjectByIdResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> GetProjectByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateProject", ReplyAction="http://tempuri.org/IEmployeeService/CreateProjectResponse")]
        EmployeeWpfClient.EmployeeServiceRef.ProjectDto CreateProject(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateProject", ReplyAction="http://tempuri.org/IEmployeeService/CreateProjectResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> CreateProjectAsync(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateProject", ReplyAction="http://tempuri.org/IEmployeeService/UpdateProjectResponse")]
        EmployeeWpfClient.EmployeeServiceRef.ProjectDto UpdateProject(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateProject", ReplyAction="http://tempuri.org/IEmployeeService/UpdateProjectResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> UpdateProjectAsync(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteProject", ReplyAction="http://tempuri.org/IEmployeeService/DeleteProjectResponse")]
        bool DeleteProject(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteProject", ReplyAction="http://tempuri.org/IEmployeeService/DeleteProjectResponse")]
        System.Threading.Tasks.Task<bool> DeleteProjectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AssignEmployeeToProject", ReplyAction="http://tempuri.org/IEmployeeService/AssignEmployeeToProjectResponse")]
        bool AssignEmployeeToProject(int employeeId, int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AssignEmployeeToProject", ReplyAction="http://tempuri.org/IEmployeeService/AssignEmployeeToProjectResponse")]
        System.Threading.Tasks.Task<bool> AssignEmployeeToProjectAsync(int employeeId, int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/RemoveEmployeeFromProject", ReplyAction="http://tempuri.org/IEmployeeService/RemoveEmployeeFromProjectResponse")]
        bool RemoveEmployeeFromProject(int employeeId, int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/RemoveEmployeeFromProject", ReplyAction="http://tempuri.org/IEmployeeService/RemoveEmployeeFromProjectResponse")]
        System.Threading.Tasks.Task<bool> RemoveEmployeeFromProjectAsync(int employeeId, int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetDepartmentWithEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetDepartmentWithEmployeesResponse")]
        EmployeeWpfClient.EmployeeServiceRef.DepartmentDto GetDepartmentWithEmployees(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetDepartmentWithEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetDepartmentWithEmployeesResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> GetDepartmentWithEmployeesAsync(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetProjectWithEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetProjectWithEmployeesResponse")]
        EmployeeWpfClient.EmployeeServiceRef.ProjectDto GetProjectWithEmployees(int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetProjectWithEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetProjectWithEmployeesResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> GetProjectWithEmployeesAsync(int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetProjectsForEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetProjectsForEmployeeResponse")]
        EmployeeWpfClient.EmployeeServiceRef.ProjectDto[] GetProjectsForEmployee(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetProjectsForEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetProjectsForEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto[]> GetProjectsForEmployeeAsync(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UploadEmployeePhoto", ReplyAction="http://tempuri.org/IEmployeeService/UploadEmployeePhotoResponse")]
        bool UploadEmployeePhoto(int employeeId, byte[] fileContents, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UploadEmployeePhoto", ReplyAction="http://tempuri.org/IEmployeeService/UploadEmployeePhotoResponse")]
        System.Threading.Tasks.Task<bool> UploadEmployeePhotoAsync(int employeeId, byte[] fileContents, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeePhoto", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeePhotoResponse")]
        byte[] GetEmployeePhoto(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeePhoto", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeePhotoResponse")]
        System.Threading.Tasks.Task<byte[]> GetEmployeePhotoAsync(int employeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : EmployeeWpfClient.EmployeeServiceRef.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<EmployeeWpfClient.EmployeeServiceRef.IEmployeeService>, EmployeeWpfClient.EmployeeServiceRef.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.DepartmentDto[] GetAllDepartments() {
            return base.Channel.GetAllDepartments();
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto[]> GetAllDepartmentsAsync() {
            return base.Channel.GetAllDepartmentsAsync();
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.DepartmentDto GetDepartmentById(int id) {
            return base.Channel.GetDepartmentById(id);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> GetDepartmentByIdAsync(int id) {
            return base.Channel.GetDepartmentByIdAsync(id);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.DepartmentDto CreateDepartment(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto) {
            return base.Channel.CreateDepartment(dto);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> CreateDepartmentAsync(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto) {
            return base.Channel.CreateDepartmentAsync(dto);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.DepartmentDto UpdateDepartment(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto) {
            return base.Channel.UpdateDepartment(dto);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> UpdateDepartmentAsync(EmployeeWpfClient.EmployeeServiceRef.DepartmentDto dto) {
            return base.Channel.UpdateDepartmentAsync(dto);
        }
        
        public bool DeleteDepartment(int id) {
            return base.Channel.DeleteDepartment(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDepartmentAsync(int id) {
            return base.Channel.DeleteDepartmentAsync(id);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[]> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[] GetEmployeesByDepartmentId(int departmentId) {
            return base.Channel.GetEmployeesByDepartmentId(departmentId);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto[]> GetEmployeesByDepartmentIdAsync(int departmentId) {
            return base.Channel.GetEmployeesByDepartmentIdAsync(departmentId);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDto GetEmployeeById(int id) {
            return base.Channel.GetEmployeeById(id);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto> GetEmployeeByIdAsync(int id) {
            return base.Channel.GetEmployeeByIdAsync(id);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDto CreateEmployee(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto) {
            return base.Channel.CreateEmployee(dto);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto> CreateEmployeeAsync(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto) {
            return base.Channel.CreateEmployeeAsync(dto);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDto UpdateEmployee(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto) {
            return base.Channel.UpdateEmployee(dto);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDto> UpdateEmployeeAsync(EmployeeWpfClient.EmployeeServiceRef.EmployeeDto dto) {
            return base.Channel.UpdateEmployeeAsync(dto);
        }
        
        public bool DeleteEmployee(int id) {
            return base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto GetEmployeeDetail(int employeeId) {
            return base.Channel.GetEmployeeDetail(employeeId);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto> GetEmployeeDetailAsync(int employeeId) {
            return base.Channel.GetEmployeeDetailAsync(employeeId);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto CreateOrUpdateEmployeeDetail(EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto dto) {
            return base.Channel.CreateOrUpdateEmployeeDetail(dto);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto> CreateOrUpdateEmployeeDetailAsync(EmployeeWpfClient.EmployeeServiceRef.EmployeeDetailDto dto) {
            return base.Channel.CreateOrUpdateEmployeeDetailAsync(dto);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.ProjectDto[] GetAllProjects() {
            return base.Channel.GetAllProjects();
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto[]> GetAllProjectsAsync() {
            return base.Channel.GetAllProjectsAsync();
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.ProjectDto GetProjectById(int id) {
            return base.Channel.GetProjectById(id);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> GetProjectByIdAsync(int id) {
            return base.Channel.GetProjectByIdAsync(id);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.ProjectDto CreateProject(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto) {
            return base.Channel.CreateProject(dto);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> CreateProjectAsync(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto) {
            return base.Channel.CreateProjectAsync(dto);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.ProjectDto UpdateProject(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto) {
            return base.Channel.UpdateProject(dto);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> UpdateProjectAsync(EmployeeWpfClient.EmployeeServiceRef.ProjectDto dto) {
            return base.Channel.UpdateProjectAsync(dto);
        }
        
        public bool DeleteProject(int id) {
            return base.Channel.DeleteProject(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProjectAsync(int id) {
            return base.Channel.DeleteProjectAsync(id);
        }
        
        public bool AssignEmployeeToProject(int employeeId, int projectId) {
            return base.Channel.AssignEmployeeToProject(employeeId, projectId);
        }
        
        public System.Threading.Tasks.Task<bool> AssignEmployeeToProjectAsync(int employeeId, int projectId) {
            return base.Channel.AssignEmployeeToProjectAsync(employeeId, projectId);
        }
        
        public bool RemoveEmployeeFromProject(int employeeId, int projectId) {
            return base.Channel.RemoveEmployeeFromProject(employeeId, projectId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveEmployeeFromProjectAsync(int employeeId, int projectId) {
            return base.Channel.RemoveEmployeeFromProjectAsync(employeeId, projectId);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.DepartmentDto GetDepartmentWithEmployees(int departmentId) {
            return base.Channel.GetDepartmentWithEmployees(departmentId);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.DepartmentDto> GetDepartmentWithEmployeesAsync(int departmentId) {
            return base.Channel.GetDepartmentWithEmployeesAsync(departmentId);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.ProjectDto GetProjectWithEmployees(int projectId) {
            return base.Channel.GetProjectWithEmployees(projectId);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto> GetProjectWithEmployeesAsync(int projectId) {
            return base.Channel.GetProjectWithEmployeesAsync(projectId);
        }
        
        public EmployeeWpfClient.EmployeeServiceRef.ProjectDto[] GetProjectsForEmployee(int employeeId) {
            return base.Channel.GetProjectsForEmployee(employeeId);
        }
        
        public System.Threading.Tasks.Task<EmployeeWpfClient.EmployeeServiceRef.ProjectDto[]> GetProjectsForEmployeeAsync(int employeeId) {
            return base.Channel.GetProjectsForEmployeeAsync(employeeId);
        }
        
        public bool UploadEmployeePhoto(int employeeId, byte[] fileContents, string fileName) {
            return base.Channel.UploadEmployeePhoto(employeeId, fileContents, fileName);
        }
        
        public System.Threading.Tasks.Task<bool> UploadEmployeePhotoAsync(int employeeId, byte[] fileContents, string fileName) {
            return base.Channel.UploadEmployeePhotoAsync(employeeId, fileContents, fileName);
        }
        
        public byte[] GetEmployeePhoto(int employeeId) {
            return base.Channel.GetEmployeePhoto(employeeId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetEmployeePhotoAsync(int employeeId) {
            return base.Channel.GetEmployeePhotoAsync(employeeId);
        }
    }
}
